services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
    ports:
      - "5432:5432"
    volumes:
      - ~/dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  limeapi:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      JWT_SECRET: secret
    container_name: limeapi
    ports:
      - '4000:3000'
    command: npm run dev
    depends_on:
      db:
        condition: service_healthy